# Generated by Django 4.1.3 on 2022-11-25 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_title_product_name_remove_product_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='index',
            field=models.IntegerField(null=True, verbose_name='Индекс'),
        ),
    ]
