# Generated by Django 4.1.3 on 2022-11-29 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_calories_alter_product_cm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='index',
        ),
    ]
