# Generated by Django 4.1.3 on 2022-12-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cm',
            field=models.IntegerField(default=25),
        ),
    ]
