# Generated by Django 4.1.3 on 2022-12-01 05:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_product_cm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999, message='LOH EBANY')]),
        ),
    ]
