# Generated by Django 4.1.3 on 2022-12-01 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_product_cm_alter_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='calories',
        ),
    ]
