# Generated by Django 4.1.3 on 2022-12-01 07:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_remove_product_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cm',
            field=models.IntegerField(default=25, validators=[django.core.validators.MaxValueValidator(40, message='Не может быть больше, чем 40')], verbose_name='Диаметр'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=110, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=24, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999, message='Не может быть больше, чем 9999')], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000, message='Не может быть больше, чем 1000')], verbose_name='Вес'),
        ),
    ]
