# Generated by Django 4.1.3 on 2022-12-12 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_product_cm_alter_product_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cm',
        ),
    ]
