# Generated by Django 4.1.3 on 2022-12-12 05:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_remove_product_cm'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cm',
            field=models.IntegerField(default=30, validators=[django.core.validators.MaxValueValidator(40, message='Не может быть больше, чем 40')], verbose_name='Диаметр'),
        ),
    ]
